// Moroccan cities list sourced from countriesnow API
// https://countriesnow.space/api/v0.1/countries

export const MOROCCO_CITIES: string[] = [
  'Casablanca',
  'Rabat',
  'Fes',
  'Marrakesh',
  'Tangier',
  'Agadir',
  'Meknes',
  'Oujda',
  'Kenitra',
  'Tetouan',
  'Safi',
  'Mohammedia',
  'Khouribga',
  'Beni Mellal',
  'El Jadida',
  'Nador',
  'Taza',
  'Settat',
  'Larache',
  'Ksar El Kebir',
  'Guelmim',
  'Dakhla',
  'Laayoune',
  'Errachidia',
  'Ouarzazate',
  'Taroudant',
  'Tiznit',
  'Berkane',
  'Taourirt',
  'Ouezzane',
  'Azrou',
  'Ifrane',
  'Midelt',
  'Khemisset',
  'Sidi Kacem',
  'Sidi Slimane',
  'Sidi Bennour',
  'Youssoufia',
  'Bouznika',
  'Tiflet',
  'Bouskoura',
  'Skhirat',
  'Oued Zem',
  'El Kelaa des Sraghna',
  'Kalaat M’Gouna',
  'Chefchaouen',
  'Chichaoua',
  'Sefrou',
  'Guercif',
  'Fquih Ben Salah',
  'Jerada',
  'Sidi Ifni',
];


